activation: lrelu
anneal_end: 125
anneal_end_y: 125
anneal_start: 25
anneal_start_y: 25
backbone: dtcn
backbone_generative: dtcn
backbone_inference: dtcn
batch_size: 2
best_val_epoch: 301
bidirectional: true
classifier_type: multiclass
data_config: /Users/blau/Projects/daart_utils/configs/data_ssm.yaml
data_dir: /Users/blau/Projects/daart_utils/data/ssm/
device: cpu
dropout: 0.1
early_stop_history: 5
enable_early_stop: true
expt_dir: /Users/blau/Projects/daart/results_gmdgm/ssm_v1
expt_ids:
- ssm_v1
gpus_vis: 0
hpc_exp_number: null
ignore_class: -1
input_size: 10
input_type: markers
kl_weight: 0.1
kl_y_weight: 10
kl_y_weight_uniform: 1
l2_reg: 0
lambda_pred: 1
lambda_recon: 0
lambda_strong: 50
lambda_task: 0
lambda_weak: 0
learning_rate: 0.001
max_epochs: 5003
min_epochs: 300
model_class: rslds
model_config: /Users/blau/Projects/daart_utils/configs/model_ssm.yaml
model_dir: /Users/blau/Projects/daart/results_gmdgm/ssm_v1/dtcn/
n_aug_classes: 0
n_hid_layers: 2
n_hid_units: 2
n_lags: 4
n_observed_classes: 4
n_total_classes: 4
output_size: 4
plot_train_curves: true
prob_threshold: 0.9
py_1_logits:
- -1.09861
- -1.09861
- -1.09861
- -1.09861
pz_1_logvar: -9.21
pz_1_mean:
- 0
- 1
qy_x_temperature: 1
results_dir: /Users/blau/Projects/daart/results_gmdgm/
rng_seed_model: 0
rng_seed_train: 0
save_last_model: false
semi_supervised_algo: null
sequence_length: 500
sequence_pad: 24
train_config: /Users/blau/Projects/daart_utils/configs/train_ssm.yaml
train_frac: 1
training_completed: true
trial_splits: 9;1;0;0
tt_experiment_name: kl_v20
tt_n_cpu_trials: 100
tt_n_cpu_workers: 5
tt_version_dir: /Users/blau/Projects/daart/results_gmdgm/ssm_v1/dtcn/kl_v20/version_0
val_check_interval: 1
variational: false
version: 0
