activation: lrelu
anneal_end: 125
anneal_end_y: 125
anneal_start: 25
anneal_start_y: 25
backbone: dtcn
backbone_generative: dtcn
backbone_inference: dtcn
batch_size: 2
best_val_epoch: 47
bidirectional: true
classifier_type: multiclass
data_config: /home/bsb2144/daart/daart_utils/configs/data_fly.yaml
data_dir: /home/bsb2144/daart/daart_utils/data/fly/
device: cuda
dropout: 0.1
early_stop_history: 5
enable_early_stop: true
expt_dir: /home/bsb2144/daart/results_gmdgm/multi-1
expt_ids:
- 2019_08_07_fly2
- 2019_08_08_fly1
- 2019_08_20_fly2
- 2019_10_10_fly3
- 2019_10_14_fly3
gpus_vis: 0
hpc_exp_number: null
input_size: 16
input_type: markers
kl_weight: 0.1
kl_y_weight: 10
l2_reg: 0
lambda_pred: 1
lambda_recon: 0
lambda_strong: 100
lambda_task: 0
lambda_weak: 0
learning_rate: 0.0001
max_epochs: 200
min_epochs: 50
model_class: rslds
model_config: /home/bsb2144/daart/daart_utils/configs/model.yaml
model_dir: /home/bsb2144/daart/results_gmdgm/multi-1/dtcn/
n_aug_classes: 2
n_hid_layers: 2
n_hid_units: 32
n_lags: 4
n_observed_classes: 5
n_total_classes: 7
output_size: 5
plot_train_curves: true
prob_threshold: 0.9

pz_1_logvar: 0
pz_1_mean: 0
qy_x_temperature: 1
results_dir: /home/bsb2144/daart/results_gmdgm/
rng_seed_model: 0
rng_seed_train: 0
save_last_model: false
semi_supervised_algo: null
sequence_length: 500
sequence_pad: 24
train_config: /home/bsb2144/daart/daart_utils/configs/train_fly.yaml
train_frac: 1
training_completed: true
trial_splits: 9;1;0;0
tt_experiment_name: test_rsldsv6
tt_n_cpu_trials: 100
tt_n_cpu_workers: 5
tt_version_dir: /home/bsb2144/daart/results_gmdgm/multi-1/dtcn/test_rsldsv6/version_0
val_check_interval: 1
variational: false
version: 0
